/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSmartMessRouteImport } from './routes/work.smart-mess'
import { Route as WorkRakshaRouteImport } from './routes/work.raksha'
import { Route as WorkFraudRouteImport } from './routes/work.fraud'
import { Route as WorkEchoNewsRouteImport } from './routes/work.echo-news'
import { Route as WorkBinwahRouteImport } from './routes/work.binwah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSmartMessRoute = WorkSmartMessRouteImport.update({
  id: '/work/smart-mess',
  path: '/work/smart-mess',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRakshaRoute = WorkRakshaRouteImport.update({
  id: '/work/raksha',
  path: '/work/raksha',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkFraudRoute = WorkFraudRouteImport.update({
  id: '/work/fraud',
  path: '/work/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkEchoNewsRoute = WorkEchoNewsRouteImport.update({
  id: '/work/echo-news',
  path: '/work/echo-news',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkBinwahRoute = WorkBinwahRouteImport.update({
  id: '/work/binwah',
  path: '/work/binwah',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/binwah': typeof WorkBinwahRoute
  '/work/echo-news': typeof WorkEchoNewsRoute
  '/work/fraud': typeof WorkFraudRoute
  '/work/raksha': typeof WorkRakshaRoute
  '/work/smart-mess': typeof WorkSmartMessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/binwah': typeof WorkBinwahRoute
  '/work/echo-news': typeof WorkEchoNewsRoute
  '/work/fraud': typeof WorkFraudRoute
  '/work/raksha': typeof WorkRakshaRoute
  '/work/smart-mess': typeof WorkSmartMessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/binwah': typeof WorkBinwahRoute
  '/work/echo-news': typeof WorkEchoNewsRoute
  '/work/fraud': typeof WorkFraudRoute
  '/work/raksha': typeof WorkRakshaRoute
  '/work/smart-mess': typeof WorkSmartMessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/work/binwah'
    | '/work/echo-news'
    | '/work/fraud'
    | '/work/raksha'
    | '/work/smart-mess'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/work/binwah'
    | '/work/echo-news'
    | '/work/fraud'
    | '/work/raksha'
    | '/work/smart-mess'
  id:
    | '__root__'
    | '/'
    | '/work/binwah'
    | '/work/echo-news'
    | '/work/fraud'
    | '/work/raksha'
    | '/work/smart-mess'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkBinwahRoute: typeof WorkBinwahRoute
  WorkEchoNewsRoute: typeof WorkEchoNewsRoute
  WorkFraudRoute: typeof WorkFraudRoute
  WorkRakshaRoute: typeof WorkRakshaRoute
  WorkSmartMessRoute: typeof WorkSmartMessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/smart-mess': {
      id: '/work/smart-mess'
      path: '/work/smart-mess'
      fullPath: '/work/smart-mess'
      preLoaderRoute: typeof WorkSmartMessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/raksha': {
      id: '/work/raksha'
      path: '/work/raksha'
      fullPath: '/work/raksha'
      preLoaderRoute: typeof WorkRakshaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/fraud': {
      id: '/work/fraud'
      path: '/work/fraud'
      fullPath: '/work/fraud'
      preLoaderRoute: typeof WorkFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/echo-news': {
      id: '/work/echo-news'
      path: '/work/echo-news'
      fullPath: '/work/echo-news'
      preLoaderRoute: typeof WorkEchoNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/binwah': {
      id: '/work/binwah'
      path: '/work/binwah'
      fullPath: '/work/binwah'
      preLoaderRoute: typeof WorkBinwahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkBinwahRoute: WorkBinwahRoute,
  WorkEchoNewsRoute: WorkEchoNewsRoute,
  WorkFraudRoute: WorkFraudRoute,
  WorkRakshaRoute: WorkRakshaRoute,
  WorkSmartMessRoute: WorkSmartMessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
