/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSmartMessRouteImport } from './routes/work.smart-mess'
import { Route as WorkBinwahRouteImport } from './routes/work.binwah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSmartMessRoute = WorkSmartMessRouteImport.update({
  id: '/work/smart-mess',
  path: '/work/smart-mess',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkBinwahRoute = WorkBinwahRouteImport.update({
  id: '/work/binwah',
  path: '/work/binwah',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/binwah': typeof WorkBinwahRoute
  '/work/smart-mess': typeof WorkSmartMessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/binwah': typeof WorkBinwahRoute
  '/work/smart-mess': typeof WorkSmartMessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/binwah': typeof WorkBinwahRoute
  '/work/smart-mess': typeof WorkSmartMessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work/binwah' | '/work/smart-mess'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work/binwah' | '/work/smart-mess'
  id: '__root__' | '/' | '/work/binwah' | '/work/smart-mess'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkBinwahRoute: typeof WorkBinwahRoute
  WorkSmartMessRoute: typeof WorkSmartMessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/smart-mess': {
      id: '/work/smart-mess'
      path: '/work/smart-mess'
      fullPath: '/work/smart-mess'
      preLoaderRoute: typeof WorkSmartMessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/binwah': {
      id: '/work/binwah'
      path: '/work/binwah'
      fullPath: '/work/binwah'
      preLoaderRoute: typeof WorkBinwahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkBinwahRoute: WorkBinwahRoute,
  WorkSmartMessRoute: WorkSmartMessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
